apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projectinitializequota.redhatcop.redhat.io
spec:
  group: redhatcop.redhat.io
  names:
    kind: ProjectInitializeQuota
    listKind: ProjectInitializeQuotaList
    plural: projectinitializequota
    singular: projectinitializequota
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ProjectInitializeQuota is the Schema for the projectinitializequota
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ProjectInitializeQuotaSpec defines the desired state of ProjectInitializeQuota
          properties:
            cpu:
              type: string
            memory:
              type: string
            pods:
              type: string
          required:
          - cpu
          - memory
          - pods
          type: object
        status:
          description: ProjectInitializeQuotaStatus defines the observed state of
            ProjectInitializeQuota
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
