kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-initialize
subjects:
- kind: ServiceAccount
  name: project-initialize
roleRef:
  kind: Role
  name: project-initialize
  apiGroup: rbac.authorization.k8s.io
